### ISSUE TITLE
Dashboard: Is memory consumption value correct?

### ISSUE THREAD

**Issue by windkh** [zottelbeyer/QNAP-collectdinfluxdbgrafana#10]
Thanks for providing this bundle. Great work, ran out of the box!
![Memory](https://user-images.githubusercontent.com/10910767/104134409-9af05a00-5389-11eb-8be8-e2323a5bec76.jpg)

After having a closer look at the numbers I am a little bit curious about the memory consumption value, because the number does not match the value QNAP shows in the resource monitor:

Any idea?

**Comment by zottelbeyer** [comment]
If you take a look at the query of the RAM Panel you can see that I measure "non-free" memory, whereas QNAP measures "usable" memory. 

![image](https://user-images.githubusercontent.com/3685916/104173519-2c051680-5406-11eb-9811-07c594bfabee.png)

![image](https://user-images.githubusercontent.com/3685916/104173622-5c4cb500-5406-11eb-9e9d-94362247ed78.png)

If you want the dashboard to reproduce the QNAP values you can adjust the panel settings:

![image](https://user-images.githubusercontent.com/3685916/104173834-a2097d80-5406-11eb-9860-4c8187c147c0.png)

hope that helps.

**Comment by windkh** [comment]
Great thanks
