### ISSUE TITLE
How do I find my device names

### ISSUE THREAD

**Issue by logopk** [zottelbeyer/QNAP-collectdinfluxdbgrafana#12]
Hi,

on the Grafana-dashboard from the repo my DISK Usage is "N/A".
The imported dashboard from grafana.com it shows Storage "No Data" and DISK Usage "N/A".

I see that in the collectd config I have to adjust my Devices. But the one from my df -h command will not change anything.
SELECT * FROM "df_value" WHERE ("host" =~ /^QNAP-collectd$/) is empty

How can I resolve this issue? What info can I provide?

Thank You.

Peter

**Comment by zottelbeyer** [comment]
huh, the df plugin is configured to show any sdX, mdX and nvmeX devices so I'm not sure why you aren't seeing anything.
Make sure you are running the collectd container on the NAS.

as for the config: cat /proc/mdstat

```
[~] # cat /proc/mdstat
Personalities : [linear] [raid0] [raid1] [raid10] [raid6] [raid5] [raid4] [multipath]
md2 : active raid5 sdd3[0] sda3[3] sdb3[2] sdc3[1]
      17551701504 blocks super 1.0 level 5, 512k chunk, algorithm 2 [4/4] [UUUU]
      bitmap: 1/3 pages [64KB], 65536KB chunk

md1 : active raid5 sdh3[0] sde3[3] sdf3[2] sdg3[1]
      23412214272 blocks super 1.0 level 5, 512k chunk, algorithm 2 [4/4] [UUUU]
      bitmap: 2/4 pages [128KB], 65536KB chunk

md322 : active raid1 sda5[7](S) sdb5[6](S) sdc5[5](S) sdd5[4](S) sde5[3](S) sdf5[2](S) sdg5[1] sdh5[0]
      7235136 blocks super 1.0 [2/2] [UU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md256 : active raid1 sda2[7](S) sdb2[6](S) sdc2[5](S) sdd2[4](S) sde2[3](S) sdf2[2](S) sdg2[1] sdh2[0]
      530112 blocks super 1.0 [2/2] [UU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md13 : active raid1 sdh4[0] sda4[35] sdb4[34] sdc4[33] sdd4[32] sde4[3] sdf4[2] sdg4[1]
      458880 blocks super 1.0 [32/8] [UUUUUUUU________________________]
      bitmap: 1/1 pages [64KB], 65536KB chunk

md9 : active raid1 sdh1[0] sda1[35] sdb1[34] sdc1[33] sdd1[32] sde1[3] sdf1[2] sdg1[1]
      530048 blocks super 1.0 [32/8] [UUUUUUUU________________________]
      bitmap: 1/1 pages [64KB], 65536KB chunk
```


will show you (software) raid devices. you can probably ignore things like md13, md322, md256 etc. On my NAS only md1 and md2 are interesting.

Within these raids you can also see the individual devices:

```
md2 : active raid5 sdd3[0] sda3[3] sdb3[2] sdc3[1]

md1 : active raid5 sdh3[0] sde3[3] sdf3[2] sdg3[1]

```

**Comment by logopk** [comment]
```
Personalities : [linear] [raid0] [raid1] [raid10] [raid6] [raid5] [raid4] [multipath] 
md1 : active raid1 sda3[0] sdb3[1]
		 2920311616 blocks super 1.0 [2/2] [UU]
		 
md322 : active raid1 sdb5[1] sda5[0]
		 7235136 blocks super 1.0 [2/2] [UU]
		 bitmap: 0/1 pages [0KB], 65536KB chunk

md256 : active raid1 sdb2[1] sda2[0]
		 530112 blocks super 1.0 [2/2] [UU]
		 bitmap: 0/1 pages [0KB], 65536KB chunk

md13 : active raid1 sda4[0] sdb4[1]
		 458880 blocks super 1.0 [32/2] [UU______________________________]
		 bitmap: 1/1 pages [4KB], 65536KB chunk

md9 : active raid1 sda1[0] sdb1[1]
		 530048 blocks super 1.0 [32/2] [UU______________________________]
		 bitmap: 1/1 pages [4KB], 65536KB chunk

unused devices: <none>

```

Beware: I'm running on a remote monitoring system (in docker).

**Comment by logopk** [comment]
Oh and I'm seeing the disk IOPS for sda (variable disk name contains sda).

**Comment by zottelbeyer** [comment]
collectd has to run on the NAS itself. IOPS are gathered via SNMP, disk usage is gathered locally. I have not had time to migrate everything to SNMP yet.

**Comment by logopk** [comment]
OK. That explains it. Unfortunately I don't have a docker-capable QNAP (TS-269L).

 I can live with it. Everything else is more than nice. So a big Thank You for the project.
