### ISSUE TITLE
Use external influxdb, run qnap-collectd from server

### ISSUE THREAD

**Issue by mattiaoui** [zottelbeyer/QNAP-collectdinfluxdbgrafana#14]
hi, 
i see you docker-compose file and i create my compose-file from ubuntu server.
Pull correctly the container, but one question about configuration file.I see the 

<Plugin network>
	Server "127.0.0.1" "25826"
</Plugin>

how possible to change the output file to sent data direclty to influxDB?
Thanks
Mattia

**Comment by zottelbeyer** [comment]
Change the server IP in collectd.conf 

https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/blob/master/qnap-collectd/collectd.conf.d/sample.conf#L18-L20

Make sure your influxd instance accepts collectd input:

https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/blob/master/influxdb/influxdb.conf#L108-L120

**Comment by mattiaoui** [comment]
thanks...change configuration and work.
Very good project....
