### ISSUE TITLE
Not a Issue, but a question about docker container monitoring

### ISSUE THREAD

**Issue by balajeek** [zottelbeyer/QNAP-collectdinfluxdbgrafana#16]
I was looking to monitor my qnap as it was running out of memory every few days and the container station get stopped, i have unifi controller software running as a container and that get stopped.

qnap log was not really helpful in finding why i am running out of memory (16gb btw)

ended up setting this grafana and got it to work (with default user/password, i am unable to create new users though)

question is would it be possible to add all docker container to the grafana to monitor so i can see if any of the container is causing a spike in memory.
thanks for the great program.

**Comment by zottelbeyer** [comment]
There are many guides on how to monitor docker with grafana such as https://adamtheautomator.com/grafana-docker/ 
But this is out-of-scope for this repository.
