### ISSUE TITLE
Docker doesn't start with sehll command

### ISSUE THREAD

**Issue by dibummer** [zottelbeyer/QNAP-collectdinfluxdbgrafana#18]
HI,
I tried to follow the instructions, https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafa, incate to configure influxdb and grafana on my Qnap TVS682; however, after uploading the file via ssh, the docker-compose up -d command does not start docker. Could you give me some directions, thanks

**Comment by zottelbeyer** [comment]
Any specific error messages? Its hard to tell what the issue is with nothing to go on.

It might be that qnap finally updated docker to version with a new syntax:

try

    docker compose up -d

**Comment by dibummer** [comment]
[cid:8e2f7cac-8728-4f28-a830-6e877dab5252]


Hi, thanks for the reply, your suggestion worked; however, at the end of the installation and after reaching the grafana page, the default user:admin and password:admin credentials do not work, preventing access. How come?
I attach a screenshot. Thank you

________________________________
Da: zottelbeyer ***@***.***>
Inviato: giovedì 29 febbraio 2024 08:53
A: zottelbeyer/QNAP-collectdinfluxdbgrafana ***@***.***>
Cc: dibummer ***@***.***>; Author ***@***.***>
Oggetto: Re: [zottelbeyer/QNAP-collectdinfluxdbgrafana] Docker doesn't start with sehll command (Issue #18)


Any specific error messages? Its hard to tell what the issue is with nothing to go on.

It might be that qnap finally updated docker to version with a new syntax:

try

docker compose up -d

**Comment by dibummer** [comment]
I'm sorry, I only saw now that the credentials you indicated are user and password.
Thank you

________________________________
Da: zottelbeyer ***@***.***>
Inviato: giovedì 29 febbraio 2024 08:53
A: zottelbeyer/QNAP-collectdinfluxdbgrafana ***@***.***>
Cc: dibummer ***@***.***>; Author ***@***.***>
Oggetto: Re: [zottelbeyer/QNAP-collectdinfluxdbgrafana] Docker doesn't start with sehll command (Issue #18)


Any specific error messages? Its hard to tell what the issue is with nothing to go on.

It might be that qnap finally updated docker to version with a new syntax:

try

docker compose up -d

**Comment by zottelbeyer** [comment]
you are welcome. I've update the readme to reflect the change.

**Comment by dibummer** [comment]
Grazie del lavoro che hai fatto, funziona perfettamente. Bravo.
Vorrei chiederti un’informazione, per caso esiste la possibilità di poterlo utilizzarlo con home assistant (software di domotica) atteso che ho installato grafana e influxdb in home assistant.
Grazie.

Thanks for the work you did, it works perfectly. Good boy.
I would like to ask you some information, is there the possibility of using it with home assistant (home automation software) given that I have installed grafana and influxdb in home assistant.
Thank you.



[signature_2186056468]

Questo messaggio e i suoi allegati sono indirizzati esclusivamente alle persone indicate. La diffusione, copia o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono rigorosamente vietate. Qualora abbiate ricevuto questo documento per errore siete cortesemente pregati di darne immediata comunicazione al mittente e di provvedere alla sua distruzione, Grazie.

This e-mail and any attachments is confidential and may contain privileged information intended for the addressee(s) only. Dissemination, copying, printing or use by anybody else is unauthorised. If you are not the intended recipient, please delete this message and any attachments and advise the sender by return e-mail, Thanks.


Da: zottelbeyer ***@***.***>
Data: venerdì, 1 marzo 2024 alle ore 10:33
A: zottelbeyer/QNAP-collectdinfluxdbgrafana ***@***.***>
Cc: dibummer ***@***.***>, Author ***@***.***>
Oggetto: Re: [zottelbeyer/QNAP-collectdinfluxdbgrafana] Docker doesn't start with sehll command (Issue #18)

you are welcome. I've update the readme to reflect the change.
