### ISSUE TITLE
Disks seem incorrect for my model QNAP

### ISSUE THREAD

**Issue by ghost** [zottelbeyer/QNAP-collectdinfluxdbgrafana#2]
First off, great job with getting this setup and working.   I'm new to docker/influx/graphana/collectd, so go easy on me.  

Install instructions were spot on and easy to follow, so no problems getting that completed.
I have a QNAP TVS-1282.  
8 HDD, 2 M2, 4 SSD slots.
On my dashboard HDD3 - HDD6 do not show any temperature (screenshot at bottom), so I assume these 4 readings are actually the 4 SSD slots that are empty on my system.
How can I go about correcting these?  

Also, the RAM on the graphana dashboard always shows 99%.  On my QNAP dashboard, it averages around 12%.

QNAP TVS-1282 CPU/Ram Dashboard
![Screen Shot 2020-07-08 at 3 36 51 PM](https://user-images.githubusercontent.com/68032769/86977198-f4ed3a00-c130-11ea-8947-ddcea934b33c.png)

 QNAP TVS-1282 Disks:
![Screen Shot 2020-07-08 at 3 11 29 PM](https://user-images.githubusercontent.com/68032769/86976811-27e2fe00-c130-11ea-9711-8f1dd555d3ad.png)

Graphana Dashboard:
![Screen Shot 2020-07-08 at 3 31 34 PM](https://user-images.githubusercontent.com/68032769/86976826-30d3cf80-c130-11ea-987f-78a7f5c06a88.png)

Thank you!

**Comment by zottelbeyer** [comment]
Edit: Make sure to check what QNAP is actually reporting and please let me know. It might be that your NAS is using different SNMP Values so I might have to adjust the collectd config.

Control Panel -> System -> System Status -> "Hardware Information" Tab

If the System Status shows 0°C then that would be the reason why the Dashboard displays the same. The Temperature Panel currently only filters out "null" values. 

At the very top of the Dashboard you should find a dropdown Menu labeled "Temperature". Try deselecting the empty slots of hdd3 - hdd6 and see where that leads you. The Panel should automatically scale according to the selected values.

![image](https://user-images.githubusercontent.com/3685916/87007342-675a2a80-c1c2-11ea-90b3-3ea1d46834cb.png)

As for the RAM: QNAP does not account for cached / buffered memory, 

![image](https://user-images.githubusercontent.com/3685916/87007633-dcc5fb00-c1c2-11ea-85b8-824063c69daf.png)

whereas the dashboard calculation is simply 
free memory * -1 + 100

If you wish to use the same calculation as QNAP you could modify the RAM Panel:
Change "type_instance" to 'used' and remove the "math(*-1+100)" block

![image](https://user-images.githubusercontent.com/3685916/87007940-48a86380-c1c3-11ea-8ad6-51400aab49d5.png)

let me know if that helps.

**Comment by ghost** [comment]
Thank you for the update, this helps.  
I checked the Hardware Info, and attached screenshot below.  HDD are showing temp, SSD are showing 0.
At the top of the dashboard, I de-selected hdd3 - hdd6, the panel just removed those entries from the display, but did not add any additional or missing drives to the display.   Note, that on my dropdown, it was the same as your dropdown, no extra SSD or HDD entries showing.

This morning, I noticed that the RAM did drop from 99% down to 93%, so it is updating.  I didn't notice it change yesterday.   But, I was able to change the type_instance and math, so that it reflects what the QNAP shows.  

![Screen Shot 2020-07-09 at 5 30 54 AM](https://user-images.githubusercontent.com/68032769/87041073-88ad1d80-c1a6-11ea-9db0-0d52158ecd76.png)

**Comment by ghost** [comment]
Some additional info I found....
I did a select * from snmp_value on the database.
So, it appears on my QNAP HDD1-HDD2 are the M.2 devices.
HDD3-6 are the SSD
HDD7-14 are the actual HDD drives.  

![Screen Shot 2020-07-09 at 6 02 15 AM](https://user-images.githubusercontent.com/68032769/87043361-c3fd1b80-c1a9-11ea-90df-51ff6b13dff8.png)

**Comment by zottelbeyer** [comment]
It's good to know that all these temperatures are reported as "HDD".

Give this a try:
- In Grafana open the Dashboard-Settings -> Variables -> temperature
- Change the "Refresh" setting to "on Load" 
- hit Update and 
- save the Dashboard
- Refresh the page.

That might fix the variables you are able to select.

**Comment by ghost** [comment]
Bingo!  Changing the Refresh to on Load added the missing HDDs.  
Am I able to customize the HDD1, display names easily on the dashboard? So HDD1 reads as M.2 1, HDD3 reads as SDD1?
And finally, can I change the temps to display in °F vs °C?

**Comment by zottelbeyer** [comment]
> Bingo! Changing the Refresh to on Load added the missing HDDs.

Great. Will update the repo shortly.

> Am I able to customize the HDD1, display names easily on the dashboard?

You can use "overrides in the panel properties to change the display name:
![image](https://user-images.githubusercontent.com/3685916/87056206-980f8380-c205-11ea-97e6-3b49546e7cb0.png)

> can I change the temps to display in °F vs °C?

You can use the Math function and then change the unit of the field. As with any calculation in Grafana this might introduce reduced performance.
![image](https://user-images.githubusercontent.com/3685916/87056511-094f3680-c206-11ea-9f99-f5f5488e1c33.png)

**Comment by ghost** [comment]
Perfect, thanks for all the help.  This gives me a good base system to look at what else I can do with these tools.
