### ISSUE TITLE
[error] read-function of plugin 'snmp-QNAP-collectd' failed

### ISSUE THREAD

**Issue by kevinstsauveur** [zottelbeyer/QNAP-collectdinfluxdbgrafana#3]
First of all thanks a lot for this good repo. It's verry well explained!

### Problem
I have an error with qnap-collectd with the snmp.
`[2020-07-27 20:40:04] [error] snmp plugin: host QNAP-collectd: snmp_sess_synch_response failed: Timeout
[2020-07-27 20:40:04] [notice] read-function of plugin 'snmp-QNAP-collectd' failed. Will suspend it for 60.000 seconds.
[2020-07-27 20:41:04] [error] snmp plugin: host QNAP-collectd: snmp_sess_synch_response failed: Timeout
[2020-07-27 20:41:04] [notice] read-function of plugin'snmp-QNAP-collectd' failed. Will suspend it for 120.000 seconds.`

Of my knowledge, the snmp services were not activated before the installation. Here's the settings:

![2020-07-27 17_03_06-QNAPHTPC](https://user-images.githubusercontent.com/25964106/88591971-3768af00-d02b-11ea-9326-97988192e706.png)

**Impact**
This error caused the plugin to stop. Therefore I had no statistics sync.

### Temporary fix
To solve this problem I have edited the qnap-collectd/collectd.conf.d/sample.conf and removed the LoadPlugin snmp.
Now I have _some_ information but not all (No temperature, No fans data) probably caused by the snmp.

**Comment by kevinstsauveur** [comment]
### Solution:
After reading your instruction again I spotted that you made a clear instruction in your _Prerequisites_ about 
> Enable SNMPv2 on your QNAP with the default Community "snmp-collectd" and Trap address "[YOURNASIP]"

My bad for that (I'm probably more blaming language difference). This completely solve the issue.

### Suggestion:
Do you know how make Docker container start automatically on system boot?
It should be added in the readme!

Thanks!
**Keep up the good work!**

**Comment by zottelbeyer** [comment]
Good Suggestion! I just added the restart policy to the default docker-compose.
To enable it follow the update instructions in the readme.

Keep up the structured error reporting, It's appreciated :)
