### ISSUE TITLE
The stack is not autostarting between reboots

### ISSUE THREAD

**Issue by RayzerRay** [zottelbeyer/QNAP-collectdinfluxdbgrafana#5]
Hello and Thank you for this. 
I have a TS-1635AX. 
I followed your instructions and all was all working. 
I then restarted the NAS.
Nothing came back, I looked at the container station there was an entry for qnap-collectdinfluxdbgrafana-master that wouldn't start up. 
Error message:
Failed to start application.: Application not found:
qnap-collectdinfluxdbgrafana-master

The only way I could get is started was to SSH in the NAS and run docker-compose up -d from the QNAP-collectdinfluxdbgrafana-master directory.

Can you offer any suggestions to get this to autostart on reboots?
Thanks

**Comment by zottelbeyer** [comment]
The restart policy was only added about a month ago [in this commit](https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/commit/925bb111a601375896a131940ae795a2164b8b8a#diff-4e5e90c6228fd48698d074241c2ba760)

Did you update your docker-compose since then? If you use the latest version with the restart policy enabled it should survive a reboot. If not I will look into this further.

**Comment by RayzerRay** [comment]
I did the latest install as of the time of posting. I cant install git on my NAS to do the update so I removed it and did the install again, same results. 

Thanks for your reply.

**Comment by zottelbeyer** [comment]
You could try the following:

ssh into your NAS, cd to your Directory and run `docker-compose down --rmi all` to stop/cleanup the stack

In docker-compose.yml replace 

`"restart: unless-stopped" `
with
`"restart: always"`

then start the stack again: `docker-compose up -d`

Container-Station might be stopping and (failing to) start each container manually. I'm currently running a long-running job on my NAS so I can't do restart-tests atm but would be grateful if you'd be willing to test.

**Comment by RayzerRay** [comment]
Thanks, ill try that.

**Comment by zottelbeyer** [comment]
After the recent firmware update I saw the containers coming back up with the restart policy "always". Will update the source in a second. Please reopen this issue if you are still experiencing this issue after the change.
