### ISSUE TITLE
No Temp/Fan values available

### ISSUE THREAD

**Issue by cc13com** [zottelbeyer/QNAP-collectdinfluxdbgrafana#8]
Hi,

Thanks for your project. I installed it on my QNAP NASF7A7F4 with v4.5.1. As I can see all values are showing in Grafana except Temp and FAN.

In the qnap-collectd log is listed this error message:

```
[2020-11-23 12:10:00] [error] snmp plugin: host QNAP-collectd: snmp_sess_synch_response failed: Timeout


[2020-11-23 12:10:00] [notice] read-function of plugin `snmp-QNAP-collectd' failed. Will suspend it for 60.000 seconds.```

**Comment by zottelbeyer** [comment]
Did you enable SNMP on your NAS as specified in the readme?

`Enable SNMPv2 on your QNAP with the default Community "snmp-collectd" and Trap address "[YOURNASIP]"`

**Comment by cc13com** [comment]
It was enabled, but I forgot to change the Community string to my "public" in the .conf file. Wondering that I have seen other values. But now it looks good. Thanks.

**Comment by zottelbeyer** [comment]
Yeah, right now only a few values are gathered via SNMP, hence the need to run the container on the NAS itself.
